<a href="https://colab.research.google.com/github/MarcioSilva007/Python_Para_Iniciantes/blob/main/Computacao_cientifica_Scipy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Calcular matriz inversa com linalg do Scipy

In [2]:
import numpy as np
from scipy import linalg

matrizA= np.array([[3,0,2], [9,1,7], [1,0,1]])

#calcula a matriz inversa
ainversa = linalg.inv(matrizA)
print('\n\nMatrizA:\n\n', matrizA)
print('\n\nMatriz ainversa\n\n', ainversa)



MatrizA:

 [[3 0 2]
 [9 1 7]
 [1 0 1]]


Matriz ainversa

 [[ 1.  0. -2.]
 [-2.  1. -3.]
 [-1.  0.  3.]]


In [23]:
import numpy as np
from scipy import linalg

matrizA = np.array ([[3, 0, 2],[9, 1, 7],[1, 0, 1]])

ainversa = linalg.inv(matrizA)

#faz a comparação para ver se a matriz a e b o resultado é a matriz identidade
b = matrizA.dot(ainversa)

print('Matriz identidade:\n',b.round(1))

Matriz identidade:
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


In [34]:
# temos a seguinte equação linear
#x + y  + z = 6
#8x + 3y - z = 8
#2x -3y + z = 12

#resolução desse problema
import numpy as np
from scipy import linalg
a = np.array([[1,1,1], [8, 3,-1],[2,-3,1]])
b = np.array ([[6],[8], [12]])

#calculando matriz inversa
ainversa = linalg.inv(a)

#calculando a matriz identidade

c = ainversa.dot(b)

print(c)
print('Valor da varial x:', round(c[0][0],2))
print('Valor da variavel y:', round(c[1][0],2))
print('Valor da varial z:', round(c[2][0],2))


[[ 2.]
 [-1.]
 [ 5.]]
Valor da varial x: 2.0
Valor da variavel y: -1.0
Valor da varial z: 5.0


In [35]:
import numpy as np
from scipy import linalg
a = np.array([[1,1,1], [8, 3,-1],[2,-3,1]])
b = np.array ([[6],[8], [12]])

#calculando matriz inversa
ainversa = linalg.inv(a)

#calculando a matriz identidade

c = np.linalg.solve(a,b)

print(c)
print('Valor da varial x:', round(c[0][0],2))
print('Valor da variavel y:', round(c[1][0],2))
print('Valor da varial z:', round(c[2][0],2))


[[ 2.]
 [-1.]
 [ 5.]]
Valor da varial x: 2.0
Valor da variavel y: -1.0
Valor da varial z: 5.0


#Determinante

In [44]:
import numpy as np
from scipy import linalg

A = np.array([[8]])
B = np.array([[4,2],[3,3]])
C = np.array([[1,4,2],[1,3,3],[2,6,1]])

print('Matriz a:\n\n', A)
print('\n\nDeterinante de a:\n\n')
res = round(np.linalg.det(A),2)
print(res)

print('\n\nMatriz b:\n\n',B)
print('\n\nDeterminante de b:\n\n')
resb = round(np.linalg.det(B),2)
print(resb)


print('\n\nMatriz c:\n\n',C)
print('\n\nDeterminante de C:\n\n')
resc = round(np.linalg.det(C),2)
print(resc)


Matriz a:

 [[8]]


Deterinante de a:


8.0


Matriz b:

 [[4 2]
 [3 3]]


Determinante de b:


6.0


Matriz c:

 [[1 4 2]
 [1 3 3]
 [2 6 1]]


Determinante de C:


5.0


In [46]:
import numpy as np

from scipy import linalg

A = np.array([[2,6],[1,2]])

B = linalg.inv(A)

C = A.dot(B)

print(C[0][0]+C[1][1])

2.0
