<a href="https://colab.research.google.com/github/MarcioSilva007/Python_Para_Iniciantes/blob/main/Matrizes_NumpyMultidimensional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
#criando matriz
matriz = np.array([[1,2,3],[4,5,6],[7,8,9],[10,20,30]])

#vendo matriz
print("\nMatriz:\n",matriz)

#procurando elemnto 1 da segunda posicao lembrando que a linha e coluna começa em 0
print("\nElemento posicao (1,2):\n",matriz[1][2])

#mostrando dimensões
print("\nDimensoes:",matriz.ndim)
#alterando a linha 3 coluna 1 para o caractere alfanumerico 18
matriz[3][1] = 18
print("\nMatriz:\n",matriz)


Matriz:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]

Elemento posicao (1,2):
 6

Dimensoes: 2

Matriz:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 18 30]]


In [7]:
import numpy as np

#criando matrizes
matriz01 = np.array ([[1,2,3,], [4,5,6], [7,8,9],[10,20,30]])
matriz02 = np.array ([[2,2,2,], [6,9,-10], [1,7,9], [32,6,8]])
matriz03 = np.array ([[2,2], [0,4], [2,2]])

In [8]:
matrizsoma = matriz01 + matriz02
matrizsub = matriz01 - matriz02
matrizprod = matriz01.dot(matriz03)

In [13]:
print('\n\nMatriz01:\n\n', matriz01)
print('\n\nMatriz02:\n\n', matriz02)
print('\n\nMatriz03:\n\n', matriz03)



Matriz01:

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]


Matriz02:

 [[  2   2   2]
 [  6   9 -10]
 [  1   7   9]
 [ 32   6   8]]


Matriz03:

 [[2 2]
 [0 4]
 [2 2]]


In [12]:
print('\n\nMatrizSoma: da matriz 01 e 02:\n\n', matrizsoma)
print('\n\nMatrizSub: da matriz 01 e 02\n\n', matrizsoma)
print('\n\nProdtudo da matriz 01 x matriz 03 :\n\n', matrizsoma)



MatrizSoma: da matriz 01 e 02:

 [[ 3  4  5]
 [10 14 -4]
 [ 8 15 18]
 [42 26 38]]


MatrizSub: da matriz 01 e 02

 [[ 3  4  5]
 [10 14 -4]
 [ 8 15 18]
 [42 26 38]]


Prodtudo da matriz 01 x matriz 03 :

 [[ 3  4  5]
 [10 14 -4]
 [ 8 15 18]
 [42 26 38]]


###Concatenar e dividir matrizes


In [16]:
import numpy as np
matriz01 = np.array ([[1,2,3,], [4,5,6], [7,8,9],[10,20,30]])
matriz02 = np.array ([[2,2,2,], [6,9,-10], [1,7,9], [32,6,8]])
matriz03 = np.zeros ((1,3))

#concatenando a matriz
matrizresultante = np.concatenate((matriz01, matriz02, matriz03))

In [18]:
print('\n\nMatriz01:\n\n', matriz01)
print('\n\nMatriz02:\n\n', matriz02)
print('\n\nMatriz03:\n\n', matriz03)
print('\n\nMatriz concatenada\n\n', matrizresultante)



Matriz01:

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]


Matriz02:

 [[  2   2   2]
 [  6   9 -10]
 [  1   7   9]
 [ 32   6   8]]


Matriz03:

 [[0. 0. 0.]]


Matriz concatenada

 [[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  20.  30.]
 [  2.   2.   2.]
 [  6.   9. -10.]
 [  1.   7.   9.]
 [ 32.   6.   8.]
 [  0.   0.   0.]]


###Divinida as matrizes

In [19]:
import numpy as np

matriz01 = np.array ([[1,2,3], [4,5,6], [7,8,9], [10,20,30]])

#quebrando matrizes em partes
matrizresultante = np.split(matriz01, 2)

In [21]:
print('Matriz 01\n\n', matriz01)

Matriz 01

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]


In [23]:
print('Matriz resultante parte 01:\n\n', matrizresultante[0])

Matriz resultante parte 01:

 [[1 2 3]
 [4 5 6]]


In [24]:
print('Matriz Resultante parte 02:\n\n', matrizresultante[1])

Matriz Resultante parte 02:

 [[ 7  8  9]
 [10 20 30]]


In [25]:
#nao da para fazer isso pois no split quebramos em duas partes
print('Matriz resultante parte 03:\n\n', matrizresultante[2])

IndexError: ignored

###Matriz transposta

In [30]:
#importando a blibioteca
import numpy as np

#criando a matriz
matriz01 = np.array([[10, 20],[30,40],[50,60],[70,80]])

#criando variavel para transformar em uma matriz transposta
matriztransposta = matriz01.transpose()
#ou matriztransposta = np.transpose(matriz01)

print('Matriz normal:\n\n', matriz01)
print('Matriz transposta:\n\n', matriztransposta)

Matriz normal:

 [[10 20]
 [30 40]
 [50 60]
 [70 80]]
Matriz transposta:

 [[10 30 50 70]
 [20 40 60 80]]


####sum(): soma os elementos de uma matriz

####min(): recupera o menor elemento da matriz

####max(): recupera o maior elemento da matriz

####ptp(): apresenta a diferença entre o maior elemento da matriz e o menor elemento da matriz

####mean(): média aritmética entre os elementos da matriz

####var(): variância entre os elementos da matriz

####std(): variância entre os elementos da matriz

In [31]:
import numpy as np


matriz = np.array([[1,2,3], [4,5,6],[7,8,9], [55,80,65]])

print('Maior valor:', matriz.max())
print('Menor valor:', matriz.min())
print('Comparação entre menor e maior valor da matriz:', matriz.ptp())
print('Soma da matriz:', matriz.sum())
print('Média entre os elementos da matrizes:', matriz.mean())
print('Variância entre os elementos das matrizes', matriz.var())
print('Variancia entre os elementos da matriz:', matriz.std())




Maior valor: 80
Menor valor: 1
Comparação entre menor e maior valor da matriz: 79
Soma da matriz: 245
Média entre os elementos da matrizes: 20.416666666666668
Variância entre os elementos das matrizes 744.4097222222222
Variancia entre os elementos da matriz: 27.28387293296577


#Redimensionar Matrizes
####resize:resize consegue fazer o oposto do reshape conseguindo criar matrizes sem que as dimensoes sejam as mesmas

####reshape: não altera os valores das matrizes

In [36]:
import numpy as np

matriz = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print('\n\nMatriz antes do reshape:\n\n', matriz)
print('\n\nReshape:\n\n', matriz.reshape(5,3))
print('\n\nMatriz após reshape:\n\n', matriz)
print('\n\nResize:\n\n', matriz.resize(8,2))
print('\n\nMatriz após resize:\n\n', matriz)



Matriz antes do reshape:

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Reshape:

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Matriz após reshape:

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Resize:

 None


Matriz após resize:

 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15  0]]
