<a href="https://colab.research.google.com/github/MarcioSilva007/Python_Para_Iniciantes/blob/main/Vetores_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Criando vetores em NumPy
####dtype - indicará qual o tipo de dado dos valores armazenados no vetor.

####size - retorna a quantidade de elementos do vetor e/ou matriz.

####itemsize - retorna o tamanho de um elemento da matriz em bytes

####ndim - retornará o número de dimensões da matriz

In [ ]:
#Importando blibioteca NumPy
import numpy as np

#exemplo de vetor
vetor = np.array([8, 34, 67, 98])

#imprimindo os dados do mesmo

#imprime o que tem no vetor
print(vetor)

#imprime quantas colunas tem o vetor
print('Shape:', vetor.shape)

#imprime que a variavel armazenada é do tipo inteiro tendo 64 bit de capacidade
print('\nDtype:', vetor.dtype)

#indica que armazena 4 byts para armazenar cada elemento do vetor
print('\nSize:', vetor.size)

#retorna quanto elemento tem no vetor
print('\nItemSize:', vetor.itemsize)

#mostra quantas dimensoes tem esse vetor
print('\nNdim:', vetor.ndim)

[ 8 34 67 98]
Shape: (4,)

Dtype: int64

Size: 4

ItemSize: 8

Ndim: 1


In [ ]:
#Importando blibioteca NumPy
import numpy as np

#exemplo de vetor
vetor = np.array([8.87, 34, 67.89, 98,1.09])

#imprimindo os dados do mesmo
print(vetor)

print('\nShape:', vetor.shape)
print('\nDtype:', vetor.dtype)
print('\nSize:', vetor.size)
print('\nItemSize:', vetor.itemsize)
print('\nNdim:', vetor.ndim)

[ 8.87 34.   67.89 98.    1.09]

Shape: (5,)

Dtype: float64

Size: 5

ItemSize: 8

Ndim: 1


#Acessando e alterando vetores

In [ ]:
import numpy as np

vetor = np.array([8,34,67,98])

print('Vetor posicao[0]:', vetor[0])
print('Vetor pósicao [2]', vetor[2])
vetor[1] = 231
vetor[3] = 102
print(vetor)

Vetor posicao[0]: 8
Vetor pósicao [2] 67
[  8 231  67 102]


#Criação de vetores
####empty-(quantidade de elementos, tiposde dados) criar matrizes com valores vazios
####zeros-(quantidade de elementos, tipos de dados) criar matrizes com valores igual a zero
###ones-(quantidade de elementos, tipos de dados) criar matrizes com valores unifomemente distribuidos

In [ ]:
import numpy as np


vetor01 = np.empty([10],int)
print(vetor01)

vetor02 = np.zeros(10)
print(vetor02)

vetor03 = np.ones(10)
print(vetor03)

vetor04 = np.arange(2,13,2,float);
print(vetor04)

vetor05 = 6*np.random.random(5);
print(vetor05)

[4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 2.  4.  6.  8. 10. 12.]
[3.54019891 2.12523379 4.16155777 0.08742459 2.38983267]
